version: "3"
services:
  nginx:
    build: ./nginx
    networks:
      - my-network
    ports:
      - "443:443"
    restart: always

  wordpress:
    image: wordpress
    networks:
      - my-network
    volumes:
      - /home/junyojeo/data/wordpress:/var/www/html
    restart: always
    
  db:
    image: mariadb
    networks:
      - my-network
    volumes:
      - /home/junyojeo/data/db:/var/lib/mysql
    restart: always

  php-fpm:
    build: ./php-fpm
    volumes:
      - wordpress_data:/var/www/html
    restart: always

networks:
  my-network:
    driver: bridge

volumes:
  wordpress_data:
  mysql_data:
