version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - 'wp:/var/www/html'
    ports:
      - '443:443'
    networks:
      - intra
    env_file:
      - .env
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - 'wp:/var/www/html'
    ports:
      - '9000:9000'
    networks:
      - intra
    env_file:
      - .env
    restart: on-failure

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
    networks:
      - intra
    volumes:
      - 'db:/var/lib/mysql'
    ports:
      - '3306:3306'
    env_file:
      - .env
    restart: on-failure

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/mariadb'

networks:
  intra:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./db_root_password.txt
#   db_user_password:
#     file: ./db_user_password.txt
#   wordpress_admin_password:
#     file: ./wordpress_admin_password.txt
#   wordpress_user_password:
#     file: ./wordpress_user_password.txt
