version: '3.8'

services:
  nginx:
    image: nginx:1.24.0
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
    volumes:
      - 'wp:/var/www/html'
    ports:
      - '443:443'
    networks:
      - intra
    env_file:
      - .env
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    volumes:
      - 'wp:/var/www/html'
    networks:
      - intra
    env_file:
      - .env
    restart: on-failure

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    networks:
      - intra
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - .env
    restart: on-failure

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/mariadb'

networks:
  intra:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./.env
