version: "3"
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - jun-network
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - jun-network
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - jun-network
networks:
  jun-network:
