version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress on_failure: restart
    volumes:
      - 'wp:/var/www/html'
    ports:
      - '443:443'
    networks:
      - intra
    env_file:
      - .env
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    # Dockerfile이 있는 위치
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb on_failure: restart
    volumes:
      - 'wp:/var/www/html'
    networks:
      - intra
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    networks:
      - intra
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - .env
    restart: always

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/data/mariadb'

networks:
  intra:
    driver: bridge

# secrets:
#   db_root_password:
#     file: ./.env
