# MySQL Dockerfile
FROM mysql:latest
COPY ./mysql.conf /etc/mysql/mysql.conf
ENV MYSQL_ROOT_PASSWORD root_password
ENV MYSQL_DATABASE wordpress
ENV MYSQL_USER wordpress_user
ENV MYSQL_PASSWORD wordpress_password
